name: Cloudflare Tunnel 2

on: 
  workflow_dispatch:
    inputs:
      tunnel:
        description: 'Enter Tunnel No:'

jobs:
  CreateTunnel:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y curl wget

    - name: Download cloudflared installer
      run: |
        wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb -O cloudflared.deb

    - name: Install cloudflared
      run: |
        sudo dpkg -i cloudflared.deb

    - name: Install Express
      run: |
        npm install express
        npm install node-fetch
      
    - name: Run App and Create Tunnel
      run: |
        npm run start &
        tunnel_id=$(cloudflared tunnel create --url http://localhost:8080 | grep -oE '[a-zA-Z0-9]{8}-[a-zA-Z0-9]{4}-[a-zA-Z0-9]{4}-[a-zA-Z0-9]{4}-[a-zA-Z0-9]{12}')
        tunnel_info=$(cloudflared tunnel describe $tunnel_id)
        tunnel_link=$(echo "$tunnel_info" | grep -oE 'https://[a-zA-Z0-9.-]+\.trycloudflare.com')
        echo "$tunnel_link"
